# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="kaze"

# Example aliases
alias zshconfig="mvim ~/.zshrc"
alias ohmyzsh="mvim ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# plugins=(bundler git heroku pow powder rails3 rake rvm sublime terminitor thor vagrant virtualenvwrapper venv_activator)
plugins=(bundler git rvm venv_activator kaze)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
# source ~/.shell/aliases.sh
# source ~/.shell/build_flags.sh
# source ~/.shell/charset.sh
# source ~/.shell/cd_vars.sh
# source ~/.shell/editor.sh
# source ~/.shell/path_opts.sh
# source ~/.shell/services.sh
# source ~/.shell/ssh_vars.sh
# source ~/.shell/take.sh
# source ~/.shell/variables.sh

# emacs keybindings:
bindkey -e

export CLICOLOR=1;

# tmuxinator
# --------------------------------------------------------------------------- #
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# rvm
# --------------------------------------------------------------------------- #
# Load RVM into a shell session *as a function*
[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm"
rvm use default > /dev/null

clear
setprompt

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
