ZSH=$HOME/.oh-my-zsh
ZSH_THEME="kaze"

# Example aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"

plugins=(bundler git rvm venv_activator kaze)

source $ZSH/oh-my-zsh.sh
for config_file ($ZSH/custom/init/*.sh) source $config_file

# emacs keybindings:
bindkey -e

clear

PATH=$PATH:/usr/local/rvm/bin # Add RVM to PATH for scripting
[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# vim: set ft=zsh :
