ZSH=$HOME/.oh-my-zsh
ZSH_THEME="kaze"

# Example aliases
alias zshconfig="mvim ~/.zshrc"
alias ohmyzsh="mvim ~/.oh-my-zsh"

plugins=(bundler git rvm venv_activator kaze)

source $ZSH/oh-my-zsh.sh
for config_file ($ZSH/custom/init/*.sh) source $config_file

# emacs keybindings:
bindkey -v

clear

# vim: set ft=zsh :
